"""GitProvider — version control. Proposes changes; never merges them."""

from __future__ import annotations

from abc import abstractmethod
from datetime import datetime
from typing import ClassVar

from pydantic import Field

from happy.core.capability import Capability
from happy.core.ports.base import (
    CapabilityPort,
    OperationSpec,
    PortDescriptor,
    PortInput,
    PortOutput,
    ProhibitedOperationSpec,
    register_port,
)
from happy.core.provenance import ProvenanceKind
from happy.core.risk import RiskTier
from happy.core.terms import AuthRequirement, AuthScheme, CostKind, CostModel, RateLimit


class RepoRef(PortInput):
    repo: str
    """`owner/name`, or a local path identifier."""


class ReadFileRequest(PortInput):
    repo: RepoRef
    path: str
    ref: str = "HEAD"


class RepoFile(PortOutput):
    path: str
    text: str
    ref: str
    content_hash: str


class ListBranchesRequest(PortInput):
    repo: RepoRef


class BranchList(PortOutput):
    branches: tuple[str, ...]
    default_branch: str


class CreateBranchRequest(PortInput):
    repo: RepoRef
    branch: str
    from_ref: str = "HEAD"


class BranchCreated(PortOutput):
    branch: str
    head_sha: str


class CommitRequest(PortInput):
    repo: RepoRef
    branch: str
    message: str = Field(min_length=1, max_length=4096)
    files: tuple[tuple[str, str], ...]
    """(path, content) pairs."""


class CommitResult(PortOutput):
    sha: str
    branch: str
    committed_at: datetime
    files_changed: int


class PushRequest(PortInput):
    repo: RepoRef
    branch: str


class PushResult(PortOutput):
    branch: str
    remote_ref: str
    pushed_at: datetime


class OpenPullRequestRequest(PortInput):
    repo: RepoRef
    head: str
    base: str
    title: str = Field(min_length=1, max_length=256)
    body: str = ""
    draft: bool = True
    """Defaults to draft: a PR opened by an agent starts as a proposal."""


class PullRequestResult(PortOutput):
    number: int
    url: str
    state: str
    draft: bool


@register_port
class GitProviderPort(CapabilityPort):
    """Repository read and proposal-shaped write.

    An agent may branch, commit, push and open a pull request. It may not
    merge, force-push, or rewrite shared history. Every change generated by
    this system arrives as a reviewable proposal.
    """

    descriptor: ClassVar[PortDescriptor] = PortDescriptor(
        port_id="git_provider",
        version="1.0",
        summary="Read repositories and propose changes as pull requests.",
        provenance_kind=ProvenanceKind.REPOSITORY,
        auth=AuthRequirement(
            scheme=AuthScheme.BEARER_TOKEN,
            required=True,
            credential_keys=("HAPPY_GIT_TOKEN",),
            scopes=("contents:write", "pull_requests:write"),
            supports_read_only_credential=True,
            notes="Token must NOT carry admin, merge or force-push permissions.",
        ),
        rate_limit=RateLimit(requests=60, window_seconds=60),
        operations=(
            OperationSpec(
                name="read_file",
                summary="Read a file at a ref.",
                risk_tier=RiskTier.T0,
                capabilities=frozenset({Capability.REPO_READ, Capability.NETWORK_READ}),
                input_model=ReadFileRequest,
                output_model=RepoFile,
                idempotent=True,
                typical_cost=CostModel(kind=CostKind.FREE),
            ),
            OperationSpec(
                name="list_branches",
                summary="List branches and the default branch.",
                risk_tier=RiskTier.T0,
                capabilities=frozenset({Capability.REPO_READ, Capability.NETWORK_READ}),
                input_model=ListBranchesRequest,
                output_model=BranchList,
                idempotent=True,
                typical_cost=CostModel(kind=CostKind.FREE),
            ),
            OperationSpec(
                name="create_branch",
                summary="Create a working branch.",
                risk_tier=RiskTier.T1,
                capabilities=frozenset({Capability.REPO_WRITE, Capability.NETWORK_WRITE}),
                input_model=CreateBranchRequest,
                output_model=BranchCreated,
                typical_cost=CostModel(kind=CostKind.FREE),
            ),
            OperationSpec(
                name="commit",
                summary="Commit changes to a working branch.",
                risk_tier=RiskTier.T1,
                capabilities=frozenset({Capability.REPO_WRITE}),
                input_model=CommitRequest,
                output_model=CommitResult,
                typical_cost=CostModel(kind=CostKind.FREE),
            ),
            OperationSpec(
                name="push_branch",
                summary="Push a working branch to the remote.",
                risk_tier=RiskTier.T2,
                capabilities=frozenset({Capability.REPO_WRITE, Capability.NETWORK_WRITE}),
                input_model=PushRequest,
                output_model=PushResult,
                externally_visible=True,
                typical_cost=CostModel(kind=CostKind.FREE),
            ),
            OperationSpec(
                name="open_pull_request",
                summary="Open a pull request for human review.",
                risk_tier=RiskTier.T2,
                capabilities=frozenset({Capability.REPO_WRITE, Capability.NETWORK_WRITE}),
                input_model=OpenPullRequestRequest,
                output_model=PullRequestResult,
                externally_visible=True,
                typical_cost=CostModel(kind=CostKind.FREE),
            ),
        ),
        prohibited_operations=(
            ProhibitedOperationSpec(
                name="merge_pull_request",
                reason="Merging is a human decision. Generated code always gets review.",
            ),
            ProhibitedOperationSpec(
                name="force_push",
                reason="Rewriting shared history is irreversible and breaks "
                "other people's checkouts.",
            ),
            ProhibitedOperationSpec(
                name="delete_branch",
                reason="Irreversible destruction of work.",
            ),
            ProhibitedOperationSpec(
                name="push_to_default_branch",
                reason="The default branch is protected; changes arrive via PR only.",
            ),
            ProhibitedOperationSpec(
                name="change_repository_settings",
                reason="Administrative control stays with the Chairman.",
            ),
        ),
    )

    @abstractmethod
    async def read_file(self, request: ReadFileRequest) -> RepoFile: ...

    @abstractmethod
    async def list_branches(self, request: ListBranchesRequest) -> BranchList: ...

    @abstractmethod
    async def create_branch(self, request: CreateBranchRequest) -> BranchCreated: ...

    @abstractmethod
    async def commit(self, request: CommitRequest) -> CommitResult: ...

    @abstractmethod
    async def push_branch(self, request: PushRequest) -> PushResult: ...

    @abstractmethod
    async def open_pull_request(
        self, request: OpenPullRequestRequest
    ) -> PullRequestResult: ...
