"""Data provenance.

Every value that enters the system from outside carries a record of where it
came from and under what terms. Provenance is not decoration: the usage policy
cannot decide whether an artifact may be published without knowing which
sources it derives from, and a retrospective cannot honestly reconstruct a
decision without knowing what evidence existed at the time.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class ProvenanceKind(StrEnum):
    """The nature of a piece of evidence."""

    MODEL_OUTPUT = "model_output"
    """Generated by an LLM. Not evidence of anything but the model's output."""
    FETCHED_DOCUMENT = "fetched_document"
    VENDOR_API = "vendor_api"
    REPOSITORY = "repository"
    USER_SUPPLIED = "user_supplied"
    """Supplied by the Chairman. The only externally-sourced input we trust."""
    DERIVED = "derived"
    """Computed from other provenanced inputs; see `derived_from`."""
    SYSTEM_EVENT = "system_event"


class DataProvenance(BaseModel):
    """Where one piece of data came from, and what may be done with it."""

    model_config = ConfigDict(frozen=True)

    kind: ProvenanceKind
    source_id: str
    """`DataSourceMetadata.source_id`, a model id, or a repository URL."""
    retrieved_at: datetime
    uri: str | None = None
    content_hash: str | None = None
    """Hash of the retrieved bytes. Makes evidence tamper-evident."""
    license: str | None = None
    attribution: str | None = None
    derived_from: tuple[str, ...] = ()
    """Source ids this was computed from, for DERIVED provenance."""
    notes: str = ""

    @property
    def is_trusted_input(self) -> bool:
        """True only for data the Chairman supplied.

        Everything else — fetched pages, API responses, model output — is
        untrusted content and must never be treated as instructions.
        """
        return self.kind is ProvenanceKind.USER_SUPPLIED


class Evidence(BaseModel):
    """A provenanced claim.

    Research output consists of these. A claim without provenance is rejected
    by the validator rather than stored.
    """

    model_config = ConfigDict(frozen=True)

    claim: str
    provenance: DataProvenance
    excerpt: str | None = None
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
